heat_template_version: 2018-03-02

description: Parameterized template to create a single server

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: Ubuntu server 18.04
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: c1-r05-d20
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: mykey
  servername:
    type: string
    label: Server name
    description: Name of the server
    default: myserver
  networkname:
    type: string
    label: Network name
    description: Name of the network
    default: private

resources:
  myserver:
    type: OS::Nova::Server
    properties:
      name: { get_param: servername }
      key_name: { get_param: key }
      image: { get_param: image }
      flavor: { get_param: flavor }
      availability_zone: Education
      networks:
        - network: { get_param: networkname }